### ISSUE TITLE
documentation: fix typo in README.md

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-patterns#41]
The README.md contains a Markdown syntax error.

**Comment by x1B** [comment]
There is on superfluous underscore after _pattern families_.

**Comment by alex3683** [comment]
Hm, to me it seems the underscore is fine there. I would only move it in front of the dot.

Looking and the error thrown by the markdown display widget ("TypeError: undefined is not a valid argument for URI"), it has more likely something to do with the links inside of the document. github and the Markdown Preview Plugin for Google Chrome throw no error. Most probably this is just some shortcoming in the marked library used by the markdown display widget.

**Comment by alex3683** [comment]
Ticket marked as invalid. There is no syntactical error, but there seems to be a bug in [marked](https://github.com/chjj/marked) regarding relative links,
