### ISSUE TITLE
testing: use mockable Promise factory

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-patterns#56]
At least action handlers in LaxarJS Patterns use `$q` directly via AngularJS Injector, since they should not depend on the AngularJS module mechanism directly. But by doing this, they get a version of `$q` that is not mockable via AngularJS Mock in widget tests.
To resolve this issue and additionally be independent from AngularJS in LaxarJS Patterns, instead the new tooling factory function for Promises should be used (See LaxarJS/laxar#242).

**Comment by x1B** [comment]
Implemented on `master` (`v1.2.0`).

### Upgrade Information

LaxarJS Patterns now uses the LaxarJS tooling API (laxar#242) to obtain a $q compatible Promise-implementation. This makes it easier to support mocked $q-implementations during tests.
