### ISSUE TITLE
json-patch: use as fast-json-patch

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-patterns#60]
We currently import `fast-json-patch` as `json-patch`. Using bower it was easy to make a mapping for it. Since SystemJS handles the mapping configuration by itself, this isn't as easy anymore.
To simply avoid this problem, we should always use the package as it is named in its `package.json`, which in this case is `fast-json-patch`.

**Comment by x1B** [comment]
@alex3683 looks like this has been done some time ago:

- https://github.com/LaxarJS/laxar-patterns/blob/master/lib/resources.js#L20
- https://github.com/LaxarJS/laxar-patterns/blob/master/lib/json.js#L12

_Closing_ (feel free to reopen if this is a mistake)
