### ISSUE TITLE
flags: add publisher

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-patterns#81]
Similar to actions and resources, there should be a publisher for flags.

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`).

### New Feature

New flag publisher APIs were added for publishing flag states over the event bus in an easy way. If the flag name is a static string, use the `publisher` function:
```js
const publisher = flags.publisher( context, 'myFlag' );
```
If the flag is configurable as widget feature use the `publisherForFeature` function:
```js
const publisher = flags.publisherForFeature( context, 'someState.flag' );
```
If the configuration of the flag should be optional, simply create the publisher with the optional option:
```js
const publisher = flags.publisherForFeature( context, 'someState.flag', { optional: true } );
```
In this case, if the flag is not configured, the publisher is a noop.
The usage of all three publishers is the same: Simply call the returned function with a truthy or falsy value, which is then converted to a boolean and send over the event bus as such.
```js
publisher( true );
```
