### ISSUE TITLE
Introduce replaceRequest as resource pattern topic

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-patterns#86]
Use case: A widget is a little late to the party (yeah, its the future, where we can really lazy load widgets to popups etc. 🚀) and needs a fresh copy of some resource. By means of a `replaceRequest` it could then ask the master of the resource to do so by sending the appropriate `didReplace` event in return.
Under the hood this mechanism could even easily be built into the _replace publisher_ , which caches the latest resource version and would automatically re-send it on `replaceRequest`.

**Comment by x1B** [comment]
We're probalby going to need this feature for LaxarJS/laxar#363 an more.

Resource masters should have the options to register request-handlers, and to disable caching of resources (usually in conjunction with the former).

**Comment by alex3683** [comment]
Implemented on `master` (`v2.1.0`).

### Upgrade Information

The `resources.replacePublisherForFeature` now automatically listens for `replaceRequest` events for the configured resource. Upon receipt of that event the last published version of the resource is again published via `didReplace` event. Alternatively it is possible to turn it off or set a custom handler for such requests, both via the option `replaceRequestHandler`. If this is set to `false`, listening for `replaceRequest` events is completely disabled. In case its value is a `function`, this function is asked to return a promise for the resource to publish again via `didReplace`.
