### ISSUE TITLE
improve error messages for missing feature configuration

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-patterns#94]
For example in `resources.replacePublisherForFeature( context, 'myFeature' )`, if myFeature is not configured or if there is a typo in `'myFeature'`, an assertion fails without further information on what went wrong.
Instead there should be a clear error message stating the problem with the missing feature (or possible typo).

**Comment by x1B** [comment]
@alex3683 wanna have a look at commit 6fb1d1f -- I took the liberty to use `axContext.log` so that the widget ID/name is displayed as well.

**Comment by alex3683** [comment]
Good idea. It will for sure be helpful to have that information too.

**Comment by x1B** [comment]
@alex3683 alright. thanks, I'll merge

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
